import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import menuQuery from "@/graphql/menu";
import Footer from "@/components/Footer/Footer";
import ReduxProvider from "@/utils/reduxProvider";
import Announcement from "@/components/Header/announcement-bar/Announcement";




const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export async function generateMetadata({ title,description }) {
  if(!title){
    title= process.env.Site_Title
    description ='The React Framework for the Web'
  }
  return {
    title:process.env.homePageTitle,
    description: process.env.homePageDescription,
    applicationName: process.env.applicationName,
    metadataBase: new URL(`${process.env.BASE_URL}`),
    openGraph: {
      title: process.env.homePageTitle,
      description: process.env.homePageTitle,
      url: `${process.env.BASE_URL}`,
      siteName: `${process.env.applicationName}`,
      images: [
        {
          url: process.env.logo,
        },
      
      ],
      type: 'website',
    },
    manifest: 'https://nextjs.org/manifest.json',
  };
}

export default  function RootLayout({ children }) {

  // const mainmenu =  menuQuery(); 
  // const { menu } = mainmenu?.data
  

  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.css"/>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.css"/>
      <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"></script>
    
    <script src={process.env.BASE_URL+"/script.js"} defer />

    
    
      </head>
      <body className={inter.className}>
        <ReduxProvider>
        <Announcement />
         <Header  />
          {children}
         <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
